### ISSUE TITLE
Run without elevation in Windows

### ISSUE THREAD

**Issue by wookiefriseur** [darkdks/KF2ServerTool#9]
Just a nice to have: Being able to run it without admin privileges / UAC prompt.

I didn't have time yet to look for the reason it requires elevation. Maybe it's because of certain Windows API calls or just using maximum permissions for the files ystem access.

If I manage to understand the libraries better I can try to fix it myself and will add a PR.

**Comment by darkdks** [comment]
By default, the application requires administrator privileges because the tool deletes, creates, edits files using the Windows API, creates and kill process (such as server process). For files it is not entirely necessary, but in some cases, depending on where the server folder is located and file access rules, can lead to access problems.
So to avoid these problems, I need administrative access by default.

**Comment by wookiefriseur** [comment]
Good to know. In the other answer you mentioned novice users and that is a good point. Though by now everyone knows how to run something as admin, if there are problems. But as long as everyone has access to admin it should be fine having it required by default. 

If someone is unable to run the program because of missing admin, they can run the CMD tool. If demand for a non elevated GUI tool should ever get rise, some kind of manifest and process owner check could be implemented.

Closing it for now, thx for the quick answer.
